[tools]
node = "latest"
pnpm = "latest"

[tasks.install]
description = "Install dependencies"
run = "pnpm run install-deps"

[tasks.app]
description = "Run the application"
run = "pnpm run app"

[tasks.lint]
description = "Lint the code"
run = "pnpm run checks"

[tasks.lint-fix]
description = "Fixing linting errors"
run = "pnpm run format+fix"
