[tools]
node = "latest"
pnpm = "latest"

[tasks.install]
description = "Install dependencies"
run = "pnpm i"

[tasks.app]
description = "Run the application"
run = "pnpm app"

[tasks.lint]
description = "Lint the code"
run = "pnpm checks"

[tasks.lint-fix]
description = "Fixing linting errors"
run = "pnpm format+fix"
